### ISSUE TITLE
Price Page extra space issue

### ISSUE THREAD

**Issue by saturnonearth** [tailwindlabs/tailwindui-issues#209] opened 2020-05-27 17:19 UTC
- URL for category: [https://tailwindui.com/components/marketing/sections/pricing]( https://tailwindui.com/components/marketing/sections/pricing)

- Component name: Three tiers with emphasized tier

**Describe the bug**
There is a huge space when when viewed on smaller screen under the bullet points

**To Reproduce**
Insert code into blank HTML page on localhost machine.

**Expected behavior**
Box should resize according to content, without the extra space.

**Screenshots**
[Screenshot 1](https://pbs.twimg.com/media/EY8880HXsAEj8kW?format=jpg&name=medium)

**Browser/Device (if applicable)**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 83.0.4103.61

**Comment by jasonlbeggs** [comment] 2020-06-04 19:39
@saturnonearth I'm not able to reproduce this issue on my machine. Can you paste in your Tailwind config file and any other details that might be different in your environment?

The most likely issue is that you don't have the `@tailwindcss/ui` plugin installed as stated in the documentation. Can you check to make sure that's working? Docs here: https://tailwindui.com/documentation

**Comment by saturnonearth** [comment] 2020-06-04 19:42
I did have that issue in the beginning but then I installed the tailwindcss/ui plugin, and still no dice.

Here is my tailwind config file
`const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
  theme: {
    extend: {
      fontFamily: {
        sans: [
          'Inter var', ...defaultTheme.fontFamily.sans
        ],
      },
    },
  },
  variants: {},
  plugins: [
    require('@tailwindcss/ui'),
  ],
}
`

**Comment by jasonlbeggs** [comment] 2020-06-04 20:12
Are you using PurgeCss in your build? If so, can you paste that config as well? It might be possible that PurgeCss is removing some of the classes. It doesn't look like your Tailwind config file has any issues.

**Comment by saturnonearth** [comment] 2020-06-04 20:19
I am not using PurgeCss, just PostCss, 
[https://pastebin.com/uFaK3T7H](https://pastebin.com/uFaK3T7H)

and my  package.json
[https://pastebin.com/jgQyMxLy](https://pastebin.com/jgQyMxLy)

**Comment by simonswiss** [comment] 2020-08-10 05:45
Hi @saturnonearth 👋  - is this still an issue for you? 

If yes, would you be able to reproduce it in a little repo, CodePen or other?

**Comment by simonswiss** [comment] 2020-08-11 01:58
Gonna close this, but feel free to re-open and comment if the problem still occurs for you.

**Closed by simonswiss** 2020-08-11 01:58 UTC
Labels: bug
