### ISSUE TITLE
Component - Split with navbar - copied code not working

### ISSUE THREAD

**Issue by blauweb** [tailwindlabs/tailwindui-issues#1221] opened 2022-06-04 14:55 UTC
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/sections/heroes
- Component name:  Split with navbar

**Describe the bug**
The code copied through the "copy code" button, does not work in w fresh vite project with tailwind.
First webpack throws an error on lacking packages:
@headlessui/vue
@heroicons/vue/outline
@heroicons/vue/solid

...after installing the missing packages and chanding the dirs accordingly to the new version, webpack initializes the page without error, but the page is blank.

**To Reproduce**
1. install vite via npm
2. install tailwind in the project folder
3. init tailwind
4. setup tailwind for vue/vite as per doc instrukctions
5. copy and paste the code of the component via the copy code button after selecting VUE from the dropdown menu
6. paste code into the app.vue replacing all existing code
7. npm run dev

**Expected behavior**
I should see the component rendering on the screen of the brower- fully functional

**Screenshots**
![image](https://user-images.githubusercontent.com/38893376/172008696-05e117be-4f99-43cd-bbe3-6262d5d60285.png)

**Browser/Device (if applicable)**
 - OS: windows 10
 - Browser chrome
 - Version latest

**Additional context**

**Comment by bradlc** [comment] 2022-07-08 09:24
Hey! Can you share your project? I just copied the component into a fresh Vue/Vite project and it worked for me as expected, so must be something specific to how you have your project set up.

**Comment by reinink** [comment] 2022-07-11 18:33
Hey! I am going to close this issue since we're unable to reproduce it, but as @bradlc suggested, feel free to submit a new issue for this that include a reproduction and we'll happily take a closer look 👍

**Closed by reinink** 2022-07-11 18:33 UTC
