### ISSUE TITLE
TailWind UI Toggles

### ISSUE THREAD

**Issue by clementfleur** [tailwindlabs/tailwindui-issues#1453] opened 2023-05-10 01:04 UTC
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/toggles
- Component name: With left label and description

**Describe the bug**
![image](https://github.com/tailwindlabs/tailwindui-issues/assets/57723659/aef4c671-6baf-41af-9f60-96f59224f072)

**To Reproduce**
1. Use VueJS
2. Create a Option Component and import all component as it was done on tailwind

Expected: 
![image](https://github.com/tailwindlabs/tailwindui-issues/assets/57723659/535d3c5e-1fef-483b-9ecd-0a3931345a9c)

Actual:
![image](https://github.com/tailwindlabs/tailwindui-issues/assets/57723659/fb76708e-bd73-4aa3-9dce-2ce49552c51b)

Style applied on all the component: 
![image](https://github.com/tailwindlabs/tailwindui-issues/assets/57723659/b5ac717a-a689-4894-a508-f3d6476bea27)

**Browser/Device (if applicable)**
 - OS: WSL Ubuntu on Windows
 - Browser: Chrome
 - Version: Latest

**Comment by adamwathan** [comment] 2023-05-10 13:59
Hey! It looks like there's a lot of extra strange CSS being generated here and inserted into the document in a weird order so we'd need to see more than this to understand what's going on. Can you share a proper reproduction project? Ultimately this feels like a case of multiple CSS files being imported in different places to me but would need to see the actual project to give a recommendation on what to do instead.

**Comment by clementfleur** [comment] 2023-05-10 22:57
Sure I use vuetify using Tailwind also tailwind was configured with an alias: 'tw-'.
I think it can be linked to vuetify's library :/ 

How can I send you a proper reproduction project ?

**Comment by clementfleur** [comment] 2023-05-10 23:09
Problem resolved vuetify is a big problem like this ..
![image](https://github.com/tailwindlabs/tailwindui-issues/assets/57723659/70a9bf67-bfb9-4777-8aea-1e9bc8e86999)


Sorry about the issue, does it is possible to use it alongside with vuetify ? They didn't provide any fix for this (just put a tailwind prefix but their style ovverride tailwind :/) 
Any idea to force tailwind to take over ? 

Thanks

**Comment by reinink** [comment] 2023-05-11 12:32
@clementfleur Hey — glad you figured out what was causing the issue here. Since this isn't technically a bug with Tailwind UI I am going to close this issue.

I'd recommend jumping on our [Tailwind UI Discord channel](https://tailwindui.com/discord) or [GitHub Discussions](https://github.com/tailwindlabs/tailwindcss/discussions) for help here. We have an awesome community of people who are often willing to help out with these kinds of implementation questions.

Good luck! 💪

**Closed by reinink** 2023-05-11 12:32 UTC
