### ISSUE TITLE
Date Picker

### ISSUE THREAD

**Issue by jasonellington** [tailwindlabs/tailwindui-issues#309] opened 2020-09-02 15:59 UTC
Not sure what else to put here, other than I think it would be useful to have a datepicker input... tried using react-datepicker and all of the styling of that package was conflicting with my tailwind components

**Comment by RobinMalfait** [comment] 2020-09-02 16:44
Duplicate of #215 and #54

This suggestion was moved to the ideas column in the Trello roadmap. I'll close this but you can find this request in the roadmap here: https://trello.com/c/jVnND6De/47-date-picker 🎉

**Closed by RobinMalfait** 2020-09-02 16:44 UTC
Labels: component request
