### ISSUE TITLE
Tailwind UI Protocol Template does not hot reload

### ISSUE THREAD

**Issue by timmeade** [tailwindlabs/tailwindui-issues#1558] opened 2024-02-27 14:02 UTC
**What component (if applicable)**
- URL for category:  https://tailwindui.com/templates/protocol
- Component name:  Protocol template
- 
**Describe the bug**

Make any change to the index.mdx file and save:

```
./src/app/page.mdx
page.mdx:1:46: Could not parse import/exports with acorn

Import trace for requested module:
./src/app/page.mdx
```

**To Reproduce**
ts template 
pnpm install
p dev

**Expected behavior**
Should rebuild.   There is something going on with MDX as a lot of them other MDX templates are not working either.

**Screenshots**

**Browser/Device (if applicable)**
 - OS: MAC OS
 - Browser Chrome

**Additional context**

**Comment by reinink** [comment] 2024-02-27 19:23
Hey @timmeade, happy to try and help out here.

I've just downloaded the Protocol template, and tried installing the dependencies and running the build using pnpm, and it works without any issues for me. Making changes to the MDX files immediately updates in the browser, and I don't see any console errors. I have tried both the TypeScript and JavaScript versions of this template, and they both seem to work.

There was previously a bug when using pnpm, but that was fixed a while back (see #1512). Have you downloaded the template recently, or is it possible that you're on an older version of this template where this wasn't fixed?

Reading the MDX docs, it mentions [this specific issue](https://mdxjs.com/docs/troubleshooting-mdx/#could-not-parse-importexports-with-acorn-error): 

> This error is thrown by our MDX parser. It was introduced in version 2. It occurs when the keywords `import` or `export` are found at the start of a line but they are not followed by valid JavaScript. An example is:
> 
> ```
> import 1/1
> ```
> 
> The reason for this error is that the parser is expecting a JavaScript import or export statement. If you want the word import or export, make sure it’s not at the start of a paragraph. If you do want an import or export statement, please make sure that it’s valid JavaScript.

Is it possible that you have an invalid import in your `src/app/page.mdx` file?

**Comment by timmeade** [comment] 2024-02-27 21:06
I just downloaded it again.

Unzipped and went to the ts version

pnpm i

p dev

opened /src/app/page.mdx

changed this line to:

```
TT Getting started {{ anchor: false }}
```

Saved and got this error:

```

page.mdx:1:46: Could not parse import/exports with acorn

Import trace for requested module:
./src/app/page.mdx
```

![CleanShot 2024-02-27 at 16 02 16@2x](https://github.com/tailwindlabs/tailwindui-issues/assets/1386476/eb14bd48-75ec-4af6-b350-9fcf3cac38d7)

**Comment by timmeade** [comment] 2024-02-27 21:08
I saw that error and the issue is certainly the imports.  If i remove them all it does compile and work.   I saw that its a common error when going to MDX 2, but did not have a lot of time today to dig into it.  I'm more open tomorrow and can dig further.

**Comment by timmeade** [comment] 2024-02-27 21:10
Just saw in console:

```
<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|javascript/auto|/Users/tim/Code/labs/docs/tailwindui-protocol/protocol-ts/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js??ruleSet[1].rules[19].use[0]!/Users/tim/Code/labs/docs/tailwindui-protocol/protocol-ts/node_modules/.pnpm/@mdx-js+loader@3.0.1_webpack@5.90.3/node_modules/@mdx-js/loader/index.cjs??ruleSet[1].rules[19].use[1]!/Users/tim/Code/labs/docs/tailwindui-protocol/protocol-ts/src/app/page.mdx|rsc': No serializer registered for VFileMessage
```

**Comment by timmeade** [comment] 2024-02-28 12:20
More logs:   Still not finding issue.

```
❯ npm run dev

> tailwindui-protocol@0.1.0 dev
> next dev

   ▲ Next.js 14.0.4
   - Local:        http://localhost:3000

   automatically enabled Fast Refresh for 1 custom loader
 ✓ Ready in 1654ms
 ○ Compiling / ...
 ⨯ ./src/mdx/search.mjs
Could not parse import/exports with acorn

Import trace for requested module:
./src/mdx/search.mjs
./src/components/Search.tsx
./src/components/Header.tsx
./src/components/Layout.tsx
 ⨯ ./src/app/page.mdx
page.mdx:1:46: Could not parse import/exports with acorn

Import trace for requested module:
./src/app/page.mdx
   automatically enabled Fast Refresh for 1 custom loader
 ⨯ ./src/mdx/search.mjs
Could not parse import/exports with acorn

Import trace for requested module:
./src/mdx/search.mjs
./src/components/Search.tsx
./src/components/Header.tsx
./src/components/Layout.tsx
```

**Comment by reinink** [comment] 2024-03-21 14:19
Hey @timmeade! So really want to help you out here, but I'm following your exact steps using pnpm, on MacOS, with Chrome, and simply can't reproduce this issue.

The only way I can reproduce this is if I use an import statement in an incorrect place, like this:

```diff
- ## Getting started {{ anchor: false }}
+ import Getting started {{ anchor: false }}
```

That generates this error:

<img width="790" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/882133/64c9c2d6-e3de-45d3-b71f-df670976f098">

We've also had no one else report this issue, so somehow it's isolated to your particular setup somehow — just don't know what 😕

You said this:

> In my vscode this line appears like this:
> 
> export const sections = [ { title: 'Guides', id: 'guides' }, { title: 'Resources', id: 'resources' }, ]

However, the code from Protocol is formatted like this:

```js
export const sections = [
  { title: 'Guides', id: 'guides' },
  { title: 'Resources', id: 'resources' },
]
```

That suggests to me that somehow your code has changed between what we ship in Protocol and what you have locally. Maybe that is somehow related here? Are you 100% certain that the code that we ship in Protocol hasn't changed in your version somehow?

I am going to close this issue for now as I'm honestly not sure where to go from here, but if you're able to figure out what's causing this for you we'd love to hear.

Really sorry I cannot be more helpful than that!

**Closed by reinink** 2024-03-21 14:19 UTC
