### ISSUE TITLE
slideover overlay makes page unresponsive when it is hidden

### ISSUE THREAD

**Issue by shmish111** [tailwindlabs/tailwindui-issues#1064] opened 2021-11-12 14:48 UTC
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/overlays/slide-overs
- Component name: Slideover wide empty

**Describe the bug**
If you put a button underneath the overlay, when the overlay is hidden you cannot click the button.

**To Reproduce**
1. Add a slideover overlay
2. Add a button that is hidden by the slidover when the slideover is displayed
3. Hide the slideover
4. Try to click on the button, you cannot

**Expected behavior**
The button is clickable

**Screenshots**

**Browser/Device (if applicable)**
 - OS: [e.g. iOS] OSX
 - Browser [e.g. chrome, safari] Chrome/Brave
 - Version [e.g. 22] various recent versions

**Additional context**
we got it to work by using max-w-xl -> max-w-0 as well as transition-all (actually we will add a new transition for max-w).
we replaced
`class="w-screen max-w-2xl transform transition ease-in-out duration-500 sm:duration-700"`
with
`class="w-screen max-w-2xl transform transition-all ease-in-out duration-500 sm:duration-700"`

Also it would be nice if the comments say that you need to change `max-w-2xl` to `max-w-0` to hide the overlay.

**Comment by hilmarhalldors** [comment] 2021-12-04 10:56
Like this one

**Comment by reinink** [comment] 2022-02-28 20:06
@shmish111 Hey, so sorry for the long delay on getting back to you on this!

So the slide-over components have an invisible overlay behind them, but in front of the rest of the page. Meaning when the slide-over is open you can't click anything behind it. However, you should definitely be able to click content behind the slide-over after it's been closed.

I made a little demo where the background layer has a semi-transparent color to give you a better idea of what I mean:

https://user-images.githubusercontent.com/882133/156050651-a12ac31f-83fa-402c-a714-9f8c718b3309.mov

As you can see I am able to open the slide-over using the "Send money" button, and then close it, and then open it again without issue. Meaning — I've been unable to reproduce this issue. I know it's been a few months and you've probably moved on, but if you still need help with this, can you provide a minimal reproduction repo for me?

I am going to close this in the meantime — but feel free to post an update and I'll happily have another look 👍

**Closed by reinink** 2022-02-28 20:06 UTC
