### ISSUE TITLE
Toggle gets highlighted upon clicking

### ISSUE THREAD

**Issue by tlghnb** [tailwindlabs/tailwindui-issues#331] opened 2020-09-27 07:58 UTC
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/toggles
- Component name: Toggles

**Describe the bug**
Clicking toggles highlights the HTML element.

**To Reproduce**
1. Go to 'https://tailwindui.com/components/application-ui/forms/toggles'
2. Click on any toggles

**Expected behavior**
They shouldn't be highlighted when clicked (like no blue selection around them).

**Screenshots**
Before clicking the toggle:
<img width="100" alt="image" src="https://user-images.githubusercontent.com/1374356/94359374-7fe62c80-00af-11eb-9e45-674717461360.png">
After clicking the toggle (notice the blue selection around):
<img width="77" alt="image" src="https://user-images.githubusercontent.com/1374356/94359376-88d6fe00-00af-11eb-96db-9b8539144d50.png">
De-toggling keeps the blue selection as well:
<img width="92" alt="image" src="https://user-images.githubusercontent.com/1374356/94359377-8eccdf00-00af-11eb-8bc0-13bcdd91190e.png">
On short toggle, only the circle part gets highlighted:
<img width="75" alt="image" src="https://user-images.githubusercontent.com/1374356/94359473-1e728d80-00b0-11eb-8e9d-98290912346b.png">

**Browser/Device (if applicable)**
 - OS: [macOS Mojave 10.14.6]
 - Browser [Safari 13.1.1]

**Comment by simonswiss** [comment] 2020-09-28 06:03
Hi @tlghnb 👋

The highlight is the `focus` styles for the toggles. Just like for buttons, it is expected that the focus styles are triggered on click, since the toggle becomes in focus.

A subset of browsers support the [focus-visible](https://tailwindcss.com/docs/pseudo-class-variants#focus-visible) pseudo class variant, where you could only show the focus styles when the user interacted with the toggle via the keyboard.

But for now, the convention in Tailwind UI, as you can see in the [buttons examples](https://tailwindui.com/components/application-ui/elements/buttons), input groups, dropdowns etc, is to show the focus styles when a user clicks on an interactive element.

**Comment by simonswiss** [comment] 2020-10-02 02:29
Going to close this as it's the intended behaviour and not a bug - please re-open if you think I missed your point 👍

**Closed by simonswiss** 2020-10-02 02:29 UTC
Labels: bug
