### ISSUE TITLE
Date Picker!

### ISSUE THREAD

**Issue by abunsen** [tailwindlabs/tailwindui-issues#215] opened 2020-05-31 17:46 UTC
**Screenshots**
<img width="308" alt="Screen Shot 2020-05-31 at 1 46 06 PM" src="https://user-images.githubusercontent.com/93429/83358975-1cd4cb00-a345-11ea-92b3-f4122e8ead15.png">

**Additional context**
It would be awesome to have a date picker component and perhaps even a time picker.

**Comment by brandoncordell** [comment] 2020-06-12 07:55
Would love if this included the ability to pick a range (preferably from side by side calendars)!

**Comment by abishekrsrikaanth** [comment] 2020-06-19 19:43
I don't see any purpose in re-inventing the whole wheel. We can select a good date picker component that includes a time picker as well and find a way to just have a theme built for it through tailwind UI. Say [flatpickr](https://flatpickr.js.org/)

**Comment by inopinatus** [comment] 2020-07-24 03:15
duplicate of #54 ?

**Comment by simonswiss** [comment] 2020-08-12 03:39
Consolidating this with https://github.com/tailwindlabs/tailwindui-issues/issues/54 👍

**Closed by simonswiss** 2020-08-12 03:39 UTC
Labels: component request
