### ISSUE TITLE
Command pallet show undefined when lose focus after typing

### ISSUE THREAD

**Issue by misbahansori** [tailwindlabs/tailwindui-issues#1340] opened 2022-09-29 04:49 UTC
**JS Library**
"@headlessui/vue": "^1.7.2"

**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/navigation/command-palettes
- Component name: With images and descriptions

**Describe the bug**
When you lose focus after typing, the input displays "undefined."

**Repo**
https://github.com/misbahansori/vite-project

**To Reproduce**
1. localhost:5137
2. type anything on the search input
3. press escape
4. you will see "undefined" in the search input

**Expected behavior**
I should close the modal and clear the input

**Screenshots**
<img width="676" alt="Screen Shot 2022-09-29 at 11 47 17" src="https://user-images.githubusercontent.com/20674057/192941260-4aefaf1e-4f3f-4f9c-9017-a8466aa0819e.png">

**Browser/Device (if applicable)**
 - OS: IOS
 - Browser Chrome
 - Version 106.0

**Comment by thecrypticace** [comment] 2022-09-29 20:10
Hey! This one is caused by a Vue bug 😅 — we [merged a workaround](https://github.com/tailwindlabs/headlessui/pull/1865) for this a bit ago which you can test with our insiders if you want: `npm install @headlessui/vue@insiders`.

I'll see if we can get a tagged release out tomorrow with this and some other fixes! I'll leave this issue open until we've done the release.

**Comment by thecrypticace** [comment] 2022-09-30 16:17
We've released `@headlessui/vue@1.7.3` which fixes this bug which you can install by doing: `npm install @headlessui/vue@latest`. Thanks for reporting it!

✨

**Closed by thecrypticace** 2022-09-30 16:17 UTC
