### ISSUE TITLE
image doesn't fit the container

### ISSUE THREAD

**Issue by demonzmahmood** [tailwindlabs/tailwindui-issues#1426] opened 2023-03-10 15:16 UTC
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/marketing/page-examples/landing-pages?include=archived
- Component name:  Illustrated hero with screenshot section Archived

**Describe the bug**
the image of Testimonial section doesn't fit the container in desktop screen but fits well in mobile screen

**Expected behavior**
should fit the container in all screen sizes.

**Browser/Device (if applicable)**
 - Browser [ chrome]

**Additional context**
I copied and paste the same code in the tailwind page
<img width="1308" alt="Screen Shot 2023-03-10 at 6 15 10 PM" src="https://user-images.githubusercontent.com/87298281/224352815-05d19e93-340a-4fa5-b074-087c60e72616.png">

**Comment by adamwathan** [comment] 2023-03-10 15:34
Hey! I can't reproduce this, when I copy that chunk of the template and add the plugins as mentioned in the header comment it looks the way I'd expect:

https://play.tailwindcss.com/84AJGm4xpm

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/4323180/224357654-d35f15a2-1f95-4eaf-b636-8b74bf74879d.png">

Can you create a minimal Tailwind Play like the one I've provided that demonstrates the issue?

**Comment by demonzmahmood** [comment] 2023-03-11 08:44
it worked after removing , require('@tailwindcss/typography')

**Comment by adamwathan** [comment] 2023-03-11 11:01
I've added the typography plugin to the demo here and it still seems to work as expected for me:

https://play.tailwindcss.com/yzAIj1rhmv?file=config

Glad it's working for you now — will close this but if you do still believe it's an issue please open a new issue that includes a reproduction, that's the only way we can really help I'm afraid 👍

**Closed by adamwathan** 2023-03-11 11:01 UTC
