### ISSUE TITLE
Sidebar Hamburger button not working in mobile

### ISSUE THREAD

**Issue by guizler** [tailwindlabs/tailwindui-issues#319] opened 2020-09-10 11:27 UTC
This is bug

**Comment by simonswiss** [comment] 2020-09-14 22:48
Hey @guizler - do you have some more info on this? On what component(s) does it happen? Which browser / OS? What are the steps to reproduce?

If you provide a bit more info we'll be able to look into this issue.

Thanks! 👍

**Comment by fandiluo** [comment] 2020-09-27 13:47
I have the same problem! Please refer to it.
[https://www.youtube.com/watch?v=xd1zKRqUYUE&feature=youtu.be](Vedio)

**Comment by simonswiss** [comment] 2020-09-28 01:58
Would love to help. @fandiluo can you please specify which OS/browser/version you're on when doing this screen recording?

**Comment by fandiluo** [comment] 2020-09-28 03:11
```
OS: Windows 10
Browser: Chrome and Firefox
Version: lasted version
```
Is there anything else I can help you with?

**Comment by simonswiss** [comment] 2020-09-28 06:58
This is really useful, thank you 👍

**Comment by adamwathan** [comment] 2020-09-29 00:31
Can you please provide a GitHub repo that reproduces the issue so we can test locally? Also can you confirm that you see the error even when previewing the component at tailwindui.com, or is it only in your own project? My gut is that it's a minor markup issue when converting to React, maybe to do with an extra wrapper element introduced by the Transition component.

**Comment by fandiluo** [comment] 2020-09-29 13:29
@adamwathan @simonswiss Please check it again! Thanks.
https://github.com/fandiluo/reproduce2
-
By the way.
The layout doesn't fulfill the whole screen.
1. example
![sidebar1](https://user-images.githubusercontent.com/9468958/94564459-96041080-029a-11eb-84dc-bc142c1293fc.png)
2. mine
![sidebar2](https://user-images.githubusercontent.com/9468958/94564469-97cdd400-029a-11eb-8e03-583127cd34d1.png)

**Comment by guizler** [comment] 2020-09-29 15:37
I figure this out, thanks I'm gonna close this.

**Comment by simonswiss** [comment] 2020-09-30 06:30
Hey - glad you got it sorted 👍

Would you mind sharing what the problem was?

**Comment by simonswiss** [comment] 2020-09-30 09:21
Reopening this to address the other issue mentioned here.

**Comment by simonswiss** [comment] 2020-09-30 09:40
Hey @fandiluo!

I have [opened a PR on your repo that fixes the layout](https://github.com/fandiluo/reproduce2/pull/1). Have a look at it, it should make sense, but there is one thing I need to clarify (as I noticed a bug in our code comment positioning):

In this component, we actually show/hide the `off-canvas menu` wrapping div:

![image](https://user-images.githubusercontent.com/485747/94668786-cf4c8700-0353-11eb-8008-3f02476d8aa2.png)

The element we show/hide is actually the one above the comment - this is something we need to fix and I can see how it would have been confusing - sorry 😅

**Comment by simonswiss** [comment] 2020-10-02 01:51
Gonna close this now - @fandiluo please re-open if you still have trouble 👍

**Closed by simonswiss** 2020-10-02 01:51 UTC
Labels: bug, needs repro
