### ISSUE TITLE
Errors on page and in console for Spotlight template right out of the box

### ISSUE THREAD

**Issue by mattwrightva** [tailwindlabs/tailwindui-issues#1554] opened 2024-02-06 03:58 UTC
**Describe the bug**
Errors are appearing on the page and in the DevTools console right out of the box for the Spotlight template. 

**To Reproduce**
1. Download Spotlight template: https://tailwindui.com/templates/spotlight
2. Open a terminal for the spotlight-ts template
3. npm install
4. npm run dev
5. Open http://localhost:3000/ in a browser, and notice errors in the bottom left corner
7. Open the DevTools and look at the errors in the console

**Expected behavior**
No errors appear on the page and in the DevTools console

**Screenshots**
<img width="1452" alt="Screenshot 2024-02-05 at 8 46 37 PM" src="https://github.com/tailwindlabs/tailwindui-issues/assets/107576133/12f25203-6728-4932-866b-ee1091472d9a">
<img width="694" alt="Screenshot 2024-02-05 at 8 51 56 PM" src="https://github.com/tailwindlabs/tailwindui-issues/assets/107576133/f87a3825-5941-4a7f-b475-19ce26910aae">
<img width="979" alt="Screenshot 2024-02-05 at 8 52 03 PM" src="https://github.com/tailwindlabs/tailwindui-issues/assets/107576133/b038e433-73e5-4081-b93a-9ac304605335">
<img width="968" alt="Screenshot 2024-02-05 at 8 52 07 PM" src="https://github.com/tailwindlabs/tailwindui-issues/assets/107576133/787b6453-3791-4f92-923b-f847c2a72de3">

**Browser/Device (if applicable)**
 - OS: MacOS 14.2.1 (23C71)
 - Browser: Chrome Version 121.0.6167.139
 - Node v20.11.0
 - npm v10.2.4

**Additional context**
none

**Comment by adamwathan** [comment] 2024-02-06 11:22
Hey! Just pulled it down and set it up fresh and I can't reproduce on my end:

<img width="1498" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/4323180/d33b37ca-2865-4361-8687-c35705680dd3">

Do you mind temporarily creating a GitHub repo with exactly what you have on your machine so we can troubleshoot that?

**Comment by mattwrightva** [comment] 2024-02-07 03:15
Thank you for your quick response!

I tried again today, same result, then opened an incognito window to send a screenshot and no errors!

I think LastPass adding its little icon in the email form was the cause. Thanks again!

<img width="516" alt="Screenshot 2024-02-06 at 8 11 10 PM" src="https://github.com/tailwindlabs/tailwindui-issues/assets/107576133/02c60dec-a5ac-4a73-ac78-1c67e5def79b">

**Comment by adamwathan** [comment] 2024-02-07 11:10
Ah ok great to know! Going to close this one then since there's no actual issue with the template but glad you were able to get to the bottom of it.

**Closed by adamwathan** 2024-02-07 11:10 UTC
