### ISSUE TITLE
Inconsistent borders on callendar grid

### ISSUE THREAD

**Issue by mamaart** [tailwindlabs/tailwindui-issues#1530] opened 2023-12-18 08:36 UTC
**What component (if applicable)**
All the callendars (except the 2 last borderless examples)
https://tailwindui.com/components/application-ui/data-display/calendars

**Describe the bug**
Some of the borders in the grid are not showing.

**To Reproduce**
Open Mozilla Firefox 120.0.1 on this url:
https://tailwindui.com/components/application-ui/data-display/calendars

**Expected behavior**
Consistent borders.

**Screenshots**
![missingborder1](https://github.com/tailwindlabs/tailwindui-issues/assets/143887647/90f1d301-d819-4b33-a4b9-2b3c86252a88)
![missingborder2](https://github.com/tailwindlabs/tailwindui-issues/assets/143887647/ad0fbeb2-788f-44e3-9523-dac2e51a3972)

**Browser/Device (if applicable)**
- OS: Linux kernel 6.6.7-arch1-1
- Browser: Firefox 120.0.1

**Additional context**
nope

**Comment by adamwathan** [comment] 2023-12-18 18:01
Looked at this briefly but can't reproduce at least on macOS:

<img width="1454" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/4323180/c9c6be06-6214-4d5b-bf4b-bed45aed19c7">

Looks like we'll have to test this on Linux to see if we can reproduce there.

**Comment by reinink** [comment] 2024-01-04 15:46
@mamaart Hey! Is it possible that your browser is zoomed out? I was able to reproduce this in Firefox by zooming out:

<img width="675" alt="image" src="https://github.com/tailwindlabs/tailwindui-issues/assets/882133/23771c40-a469-4dcc-bc25-ffec5563aa87">

It's not uncommon to get these sort of rendering issues when zooming, so I'm thinking that might be what's going on here.

**Comment by reinink** [comment] 2024-01-09 17:45
Hey! Going to close this one for now since we've been unable to reproduce it, except for when zooming — which I'm hoping is the simple answer here 👍

**Closed by reinink** 2024-01-09 17:45 UTC

**Comment by mamaart** [comment] 2024-02-04 13:11
Yes my browsers default zoom lvl is 80%, that might be the reason then.
