### ISSUE TITLE
After upgrading to tailwindcss v3.0 tailwindui packages generates color errors.

### ISSUE THREAD

**Issue by iyashpal** [tailwindlabs/tailwindui-issues#1089] opened 2021-12-11 05:14 UTC
**Describe the bug**
Getting compile-time error with tailwdindcss v3.0. 

**Expected behavior**
As the tailwindui is the first party package of tailwindcss. When a new version of tailwindcss released tailwindui should have the support of that release too. 

**Screenshots**
![image](https://user-images.githubusercontent.com/19922707/145664699-d2640229-82f4-41c6-bb20-2f22123f392d.png)

**Request**
My all projects are with tailwindui and I can't use tailwindcss v3.0. Please fix it as soon as possible thanks.

**Comment by adamwathan** [comment] 2021-12-11 10:53
Hey! Not sure what the problem is here, can you share your Tailwind config file? We’ve already migrated Tailwind UI to v3 internally before releasing it and didn’t have any issues like this.

**Comment by adamwathan** [comment] 2021-12-11 14:24
Sounds like maybe you have the `@tailwindcss/ui` package installed still. That package became obsolete when Tailwind 2 was released in November 2020, and part of upgrading from Tailwind v1 to Tailwind v2 was removing that package:

https://tailwindui.com/changes-for-v2#remove-tailwindcss-ui-then-update-tailwindcss

You should be using the typography plugin directly rather than using the `@tailwindcss/ui` package nowadays, that package was basically the pre-release of Tailwind v2 and everything included in it (new colors and stuff) was merged into Tailwind by default.

**Comment by adamwathan** [comment] 2021-12-15 19:02
Going to close this as what I mentioned above is very likely the source of the issue, but if you are still having problems please don't hesitate to open another one.

**Closed by adamwathan** 2021-12-15 19:02 UTC

**Comment by iyashpal** [comment] 2021-12-17 02:41
Hey @adamwathan sorry for the late reply. It's my bad I didn't realise it before. Thank you so much.
