### ISSUE TITLE
Radio buttons in Radio Group are "squished" on Safari

### ISSUE THREAD

**Issue by uncvrd** [tailwindlabs/tailwindui-issues#668] opened 2021-06-29 08:32 UTC
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/radio-groups#component-5a30657598f3154f9bc03a680cea7ff4
- Component name: List with description

**Describe the bug**
Looks like the radio buttons get squished when reducing screen width on web/mobile safari, I was able to quickly fix this by adding `flex-shrink-0` to the following span:

```
<span
    className={classNames(
    checked ? 'bg-indigo-600 border-transparent' : 'bg-white border-gray-300',
    active ? 'ring-2 ring-offset-2 ring-indigo-500' : '',
    'h-4 w-4 mt-0.5 cursor-pointer rounded-full border flex items-center justify-center [ADD FLEX SHRINK 0 HERE]'
    )}
    aria-hidden="true"
>
```

**To Reproduce**
1. Go to the component referenced above on Safari
2. Shrink the browser
3. Observe radio button crunch

**Expected behavior**
I expect the radio button to maintain its size regardless of screen size

**Screenshots**

![image](https://user-images.githubusercontent.com/25097099/123763832-0b782e00-d879-11eb-929a-b455802d709c.png)

**Browser/Device (if applicable)**
 - OS: Mac OS Big Sur
 - Browser Safari Desktop/Mobile
 - Version 14.1.1 (on desktop)

**Additional context**
Hope that helps!

**Comment by davidluhr** [comment] 2021-08-04 16:04
@uncvrd Closing this as a duplicate of https://github.com/tailwindlabs/tailwindui-issues/issues/667, which is resolved. Thank you!

**Closed by davidluhr** 2021-08-04 16:04 UTC
Labels: bug
