### ISSUE TITLE
TailwindUI's css differs from latest

### ISSUE THREAD

**Issue by charleskhenry** [tailwindlabs/tailwindui-issues#718] opened 2021-08-29 01:48 UTC
**What component (if applicable)**
- URL for category:  https://tailwindui.com/components/marketing/elements/headers
- Component name:  "Headers" > "Centered with bottom border"

**Describe the bug**
Copying and pasting the "Centered with bottom border" component into a fresh Laravel project results in the UI not properly working.  In particular, the "solutions" and "more dialogs" will not close and automatically open.  Additionally, the buttons are centered aligned instead of being left aligned.

**Expected behavior**

**Screenshots**
https://postimg.cc/sQr9RmHG

**Browser/Device (if applicable)**
Browser: brave
Package.json
```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "mix",
        "watch": "mix watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "prod": "npm run production",
        "production": "mix --production"
    },
    "devDependencies": {
        "@tailwindcss/forms": "^0.3.3",
        "@tailwindcss/typography": "^0.4.1",
        "alpinejs": "^3.0.6",
        "autoprefixer": "^10.3.1",
        "axios": "^0.21",
        "laravel-mix": "^6.0.6",
        "lodash": "^4.17.19",
        "postcss": "^8.3.6",
        "postcss-import": "^14.0.1",
        "tailwindcss": "^2.2.7"
    },
    "dependencies": {
        "@tailwindcss/aspect-ratio": "^0.2.1",
        "install": "^0.13.0",
        "npm": "^7.20.6"
    }
}
```

**Additional context**
Upon inspection, it appears that using the latest stable version of tailwindcss (v2.2.7 ) differs from your your demo site tailwindcss (v2.2.4 ).

The UI website is very unclear of exact versions to use for tailwindcss and other dependencies.
Perhaps add a badge for each UI component providing the versions, or if it passes the latest version.

**Comment by davidluhr** [comment] 2021-08-30 16:35
@charleskhenry I have copied the component code into a fresh project and everything appears as expected.

> the "solutions" and "more dialogs" will not close and automatically open

Please note that we do not provide custom JavaScript for these components, outside of the React and Vue code, which makes use of Headless UI components. Therefore, when pasting in the plain HTML version, the menus won't open/close, and by default they are visible. The JavaScript implementation depends on the specific project.

> Additionally, the buttons are centered aligned instead of being left aligned.

This is correct. The buttons are left-aligned up till the `lg` breakpoint, and then they are center aligned. You will see this same layout in the component preview: https://tailwindui.com/components/marketing/elements/headers#component-1c0390a81b16cf5028aeff08be955766

> Upon inspection, it appears that using the latest stable version of tailwindcss (v2.2.7 ) differs from your your demo site tailwindcss (v2.2.4 ).

These dependencies share the same major and minor version, so there shouldn't be any difference between them. You are free to use the latest stable version of Tailwind CSS.

Hope this helps! Closing this issue, as everything is working as intended, but feel free to reply here with any questions and we're happy to help.

**Closed by davidluhr** 2021-08-30 16:35 UTC
Labels: bug
