### ISSUE TITLE
Hamed alrasheedi

### ISSUE THREAD

**Issue by hamed19901411** [tailwindlabs/tailwindui-issues#347] opened 2020-10-18 22:35 UTC
**What component (if applicable)**
- URL for category: 
- Component name: 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser/Device (if applicable)**

**Additional context**

**Comment by simonswiss** [comment] 2020-10-19 05:58
Hey @hamed19901411 👋

It appears like the issue creation went wrong here - the title contains your name and the body of the issue is the template placeholder.

I'll close this issue for now, but please feel free to edit with some context and re-open 👍

**Closed by simonswiss** 2020-10-19 05:58 UTC
