### ISSUE TITLE
https://tailwindui.com not scrollable

### ISSUE THREAD

**Issue by zeitvertrieb** [tailwindlabs/tailwindui-issues#1519] opened 2023-11-11 11:18 UTC
**What component (if applicable)**
- URL for category: https://tailwindui.com/
- Component name: Website

**Describe the bug**
your website has a h-full class on html / body. with this the whole page is not scrollable.

**To Reproduce**
1. Go to https://tailwindui.com/
3. Scroll down

**Expected behavior**
scrolling

**Screenshots**

**Browser/Device (if applicable)**
 - OS: Sonoma 14
 - Browser Chrome latest

**Comment by adamwathan** [comment] 2023-11-11 18:03
I can't reproduce this, we set `h-full` on the `html` element but `min-h-full` on the body so the body is taller and scrolls as expected:

https://github.com/tailwindlabs/tailwindui-issues/assets/4323180/89d8b6d2-e931-4f07-a20c-da90f9911188

Can you provide more details about your setup? Does it happen with any installed extensions disabled?

**Comment by adamwathan** [comment] 2023-11-13 11:10
Going to close this for now — if you are able to find a setup that consistently reproduces this though that you think will reproduce it for me as well please open another issue with all the necessary info and we will sort it out. Thanks!

**Closed by adamwathan** 2023-11-13 11:10 UTC
