### ISSUE TITLE
Combobox example does not work in Chrome for Android (pure HeadlessUI component does)

### ISSUE THREAD

**Issue by fullturbodev** [tailwindlabs/tailwindui-issues#1463] opened 2023-06-05 13:52 UTC
**What version of Tailwind CSS are you using?**

In my project where I first discovered this issue I use the following, but this is irrelevant because not even Combobox example on tailwindui.com works (at least the first one from the top as it's the only one I tried).

- tailwindcss: 3.3.2
- @tailwindcss/forms: 0.5.3
- @headlessui/react: 1.7.15
- react: 18.2.0

**What build tool (or framework if it abstracts the build tool) are you using?**

- next: 13.4.4

**What version of Node.js are you using?**

- v18.16.0

**What browser are you using?**

- Chrome for Android (latest)

**What operating system are you using?**

- Android on Google Pixel 5

**Reproduction URL**

- https://tailwindui.com/components/application-ui/forms/comboboxes

**Describe your issue**

- Combobox doesn't work properly in Chrome on Android but works everywhere else I tried (including desktop Chrome and Safari on iPhone).
- It doesn't work because onChange event does not fire, so the list does not get updated. This line doesn't work: `onChange={(event) => setQuery(event.target.value)}`
- The underlying native `input` event does fire correctly (if I `addEventListener("input", myHandler)` through ref to `Combobox.Input` then my custom handler gets called).
- Example on headlessui.com works correctly, but the examples on tailwindui.com do not.

**Comment by reinink** [comment] 2023-08-16 16:09
Hey! Apologies on the delay here. I'm just digging into this and trying to reproduce this issue on my end, but not having any luck. I've tried it on BrowserStack on a Google Pixel and the combobox on Tailwind UI appears to work as expected:

https://github.com/tailwindlabs/tailwindui-issues/assets/882133/167c6646-3814-481e-aa79-83b3766bbf21

I've also tried this on a physical Google Pixel 3 that I have, and it also seemed to work fine there.

Is it possible that you've made some changes to the Tailwind UI implementation that could be causing this? If yes, are you able to provide a minimal reproduction of that as a Git repo for us to reproduce the issue on our end?

Thanks!

**Comment by reinink** [comment] 2023-08-29 00:36
Hey! Going to close this one because I am unable to reproduce this issue, and we haven't had reports from others with the same issue, so hopefully it's just an isolated issue in your particular project — or even better hopefully you've been able to already fix it! 😊

**Closed by reinink** 2023-08-29 00:36 UTC
