### ISSUE TITLE
Syntax template console error

### ISSUE THREAD

**Issue by pauldjordan** [tailwindlabs/tailwindui-issues#1442] opened 2023-04-05 19:54 UTC
**What component (if applicable)**
- URL for category: https://syntax.tailwindui.com/
- Component name: Syntax template

**Describe the bug**
Displays the following error in the console: A component is changing from uncontrolled to controlled. This may be caused by the value changing from undefined to a defined value, which should not happen.

**To Reproduce**
1. Go to https://syntax.tailwindui.com/
2. Open the console

**Browser/Device (if applicable)**
Tried on Mac with Firefox and Chrome. Believe the issue is with Next.js so expecting the error to appear on all browsers.

**Comment by bradlc** [comment] 2023-04-05 21:14
Hey @pauldjordan, thanks for reporting this. The issue is fixed in the latest version of the template. For reference here's the change that was applied to the `src/components/ThemeSelector.jsx` file:

```diff
- let [selectedTheme, setSelectedTheme] = useState()
+ let [selectedTheme, setSelectedTheme] = useState(null)
```

**Closed by bradlc** 2023-04-05 21:14 UTC
