### ISSUE TITLE
Box shadow issue in Firefox

### ISSUE THREAD

**Issue by amiranagram** [tailwindlabs/tailwindui-issues#483] opened 2021-02-08 14:35 UTC
**Describe the bug**

The bottom right part of the box shadow is always thinner than the top left part.
I know it's not a tailwindcss or tailwindui bug per se, as it only happens in Firefox, but is there any workaround that you suggest?

**To Reproduce**

1. Open Firefox
2. Open tailwind UI components
3. Focus any element that has ring class

**Screenshots**

![image](https://user-images.githubusercontent.com/38536188/107233143-89e74700-6a22-11eb-8536-c85c527824ae.png)

**Comment by davidluhr** [comment] 2021-02-12 22:14
@amiranagram For some reason, I can't replicate this in Firefox in MacOS. Is this appearing in MacOS or Windows? I'm guessing there's some strange thing going on with specific combinations of browser, device, screen, viewport size, etc.

**Comment by amiranagram** [comment] 2021-02-12 22:43
@davidluhr Windows.

**Comment by davidluhr** [comment] 2021-03-05 19:13
@amiranagram I've confirmed this occurs on Windows using Firefox, as you described. Unfortunately, it seems to be a browser rendering issue. I often use this combination of OS/browser and I've seen similar things on other sites, where box shadows seemingly render with different widths on either side of an element.

For example, I was visiting https://increment.com/ the other day and notice the same thing with all their "outlined" elements, which also use a box shadow.

I've noticed this only occurs on certain screens and certain browser zoom settings, so I believe there's something odd going on with pixel rounding. Not sure there's anything with Tailwind UI we can do to solve this, unfortunately, especially since we stick with whole pixel values. Closing this issue for now, but I'll update you if there's another approach we find.

**Closed by davidluhr** 2021-03-05 19:13 UTC
Labels: bug
