### ISSUE TITLE
Adding slide-over locks browser

### ISSUE THREAD

**Issue by brianakidd** [tailwindlabs/tailwindui-issues#411] opened 2020-12-17 16:05 UTC
**What component (if applicable)**
- URL for category:  https://tailwindui.com/components/application-ui/overlays/slide-overs
- Component name: Contact list example, Wide horizontal user profile example

**Describe the bug**
When copying and pasting the html from this component into an empty Vue component, and adding to a view, the browser locks and doesn't respond to mouse clicks, scrolls, etc.

**To Reproduce**
1. Copy html for component
2. Create an empty .vue component and paste in <template>
3. Ensure component is added to the layout, view, or elsewhere
4. View on Chrome and Firefox and click, mouse-over, etc.  Browser will not respond to mouse.

**Expected behavior**
Expecting the app to respond to mouse events.

**Screenshots**
Recording: https://hauler-public.s3.amazonaws.com/tailwindui-slide-over-issue.mov

**Browser/Device (if applicable)**
 - OS: MacOS Big Sur
 - Browser chrome, firefox
 - Version: macOS 11.1, chrome 87.0.4280.88, firefox 84.0

**Additional context**
This is a Vue CLI app.  I am on Tailwindcss 2.0 using the PostCSS 7 compatibility build.  I have not implemented any javascript on the page.  I am using other Tailwind UI components successfully.

**Comment by davidluhr** [comment] 2021-01-29 21:56
@brianakidd I've created a Vue project, added the component code, wired up the close button and transitions, and everything appears/functions as expected without any performance issues in the browser.

If you have an empty view with just this component, does the issue exist? Are you perhaps able to iteratively add portions of the markup to help isolate the issue? I suspect something else is conflicting with this component, but it is hard to troubleshoot on my end on its own.

**Comment by RobinMalfait** [comment] 2021-01-31 13:00
Hey! I saw this issue and I know what the problem is. The idea about this `slide-over` component is that it sits on top of your content. You could think of it as a "modal" but positioned on the side. The actual issue here is not that the browser locks, but it is the very very first div with class `fixed inset-0`. That one will create a layer on top of everything (prohibiting you from clicking / selecting / ...). I think that if you would select text in the new slide over itself, that it would work, since it sits on top of the fixed div. 

Make sure to render that first div conditionally (using `v-show` and/or the `transition` component if you need the animations), or take away the `fixed` behaviour. If you copied the slide-over with the background overlay then it would make a bit more sense on what is going on. 

Hope this info helps!

**Comment by brianakidd** [comment] 2021-01-31 13:40
@davidluhr sorry I hadn't replied.  I saw that @RobinMalfait had replied and that's probably it.  Let's close this and I'll try what he suggested once I have time.  Thanks both of you.

**Comment by davidluhr** [comment] 2021-02-05 18:16
@RobinMalfait Good catch!

Sounds good @brianakidd, let us know if there's anything else we can help with.

**Closed by davidluhr** 2021-02-05 18:16 UTC
Labels: bug

**Comment by ordago** [comment] 2021-03-10 12:27
Hi @davidluhr, I don't understand why the issue was closed. It seems like the issue still persists.

What @RobinMalfait said solves it, wouldn't it be better if those changes were reflected in the component's code?

https://user-images.githubusercontent.com/6376814/110627546-07c17e00-819a-11eb-96e5-3fe724503486.mp4
