### ISSUE TITLE
Listbox options show horizontal scrollbar for list items of moderate length

### ISSUE THREAD

**Issue by lensbart** [tailwindlabs/tailwindui-issues#596] opened 2021-04-27 15:39 UTC
See title

Also note the misplaced tick mark, which is probably a related issue

![afbeelding](https://user-images.githubusercontent.com/20876627/116270484-6b6e2d80-a77f-11eb-8a52-f8b10efd153c.png)

**Comment by lensbart** [comment] 2021-04-27 15:50
Component: https://tailwindui.com/components/application-ui/forms/select-menus#component-8298198b136afab3bb19391ae716077f
Tailwind version: latest

Can be rectified by setting sufficient width on `Listbox.Buttton`’s immediate `div` parent, but should be possible to make it work out-of-the-box

**Comment by davidluhr** [comment] 2021-04-27 20:41
@lensbart Thanks for reporting this.

When removing the width from the Tailwind UI example, the text truncates as expected, and the icon does not overlap:

![Listbox with narrow width and text truncation](https://user-images.githubusercontent.com/16038754/116309228-5d0f1a00-a75d-11eb-9de8-7e027ec39150.png)

Not sure what is causing the horizontal overflow and overlap in your screenshot, as I'm not able to reproduce this.

You can provide a width of your choice to the Listbox, as you menitoned. We don't do this by default, because we can't predict how/where this component will be used. But, you can do the following:

Before:
```js
<Listbox value={selected} onChange={setSelected}>
      {({ open }) => (
        <>
```
After:
```js
<Listbox value={selected} onChange={setSelected}>
      {({ open }) => (
        <div class="w-full max-w-xs mx-auto">
```

You can replace `w-full max-w-xs mx-auto` with whatever suits your needs best.

I'm closing this issue for now, as I don't believe there is a fix needed in the example components, but feel free to reply if there's something we can improve.

**Closed by davidluhr** 2021-04-27 20:41 UTC
Labels: bug
