### ISSUE TITLE
Different behaviour between (Chrome, Edge, Firefox Dev) and Firefox

### ISSUE THREAD

**Issue by Wulfheart** [tailwindlabs/tailwindui-issues#274] opened 2020-08-11 12:26 UTC
**Describe the bug**
``form-input`` renders differently on Tailwind UI than on Custom forms.
````html
<div class="relative rounded-md shadow-sm">
      <input class="form-input block w-full sm:text-sm sm:leading-5" placeholder="Insert your value here">
</div>
````

**To Reproduce**
````html
<div class="grid grid-cols-16 gap-4 py-3 border-b px-4">
   <div class="col-span-1 flex items-center text-lg font-medium text-gray-700">1</div>
   <div class="col-span-2 ">
   </div>
   <div class="col-span-4">
      <selectclass="form-select block w-full pl-3 pr-10 py-2 text-base leading-6 border-gray-300 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 sm:text-sm sm:leading-5">
      <option> </option>
      </select>
   </div>
   <div class="col-span-4">
      <select class="form-select block w-full pl-3 pr-10 py-2 text-base leading-6 border-gray-300 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 sm:text-sm sm:leading-5">
         <option> </option>
      </select>
   </div>
   <div class="col-span-4">
      <div class="relative rounded-md shadow-sm">
         <input class="form-input block w-full sm:text-sm sm:leading-5" placeholder="Insert your value here">
      </div>
   </div>
   <div class="col-span-1">
      <button type="button" class="w-full h-full py-2 flex flex-grow items-center justify-center text-gray-500 hover:text-gray-800 transition duration-150 ease-in-out">
         <svg fill="none" viewBox="0 0 24 24" stroke="currentColor" class="x w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
         </svg>
      </button>
   </div>
</div>


````

**Expected behavior**
I expect the input fields to align correctly and have the same size. This works fine on Edge, Chrome and Firefox Dev. Not on Firefox.

**Screenshots**
Firefox 78.0.2: ❌
![grafik](https://user-images.githubusercontent.com/25671390/89896242-68291680-dbdd-11ea-846d-f410ab937c35.png)

Edge 84.0.522.52: ✅
![grafik](https://user-images.githubusercontent.com/25671390/89896310-8b53c600-dbdd-11ea-9e18-43b4dbbe1e7d.png)

Firefox Developer 79.0b8: ✅
![grafik](https://user-images.githubusercontent.com/25671390/89896601-01f0c380-dbde-11ea-83d0-bf3fd590b539.png)

**Browser/Device (if applicable)**
 - OS: Windows 10
 - Browser: Firefox 
 - Version: 78.0.2

**Comment by simonswiss** [comment] 2020-08-17 04:07
Hello! 👋

I tried to reproduce this issue (in browserstack, to be fair) with the same Browser/Device specs you mentioned, and it looks as it should.

![image](https://user-images.githubusercontent.com/485747/90356108-baf94700-e091-11ea-9c1a-9aab30527990.png)

Mind you, I had to change the columns to 12 because 16 column grid is not part of the default config.

Are you able to reproduce this error in a minimal example that you can share in a repo or other, so I can have a proper look?

Thanks in advance! 👍

**Comment by Wulfheart** [comment] 2020-08-24 07:54
Hey @simonswiss,

I've got a minimal example at https://github.com/Wulfheart/twui-issue-spacing.

It still looks like this:
![grafik](https://user-images.githubusercontent.com/25671390/91018375-cbf50b80-e5ef-11ea-86d0-d272b9c48266.png)

Thanks for taking the time.

**Comment by Wulfheart** [comment] 2020-09-28 12:35
@simonswiss I found out that on the same configuration also the tailwindui site is looking strange:
![grafik](https://user-images.githubusercontent.com/25671390/94432948-d7f85e00-0197-11eb-91cd-d88511b2bee6.png)

**Comment by simonswiss** [comment] 2020-10-01 06:06
Hey @Wulfheart,

Thanks for this. I can confirm I was able to replicate this problem on Windows (Firefox latest version) in your repro example, as well as in a Tailwind Playground.

![image](https://user-images.githubusercontent.com/485747/94771696-31ac9280-03fb-11eb-84c0-7e9130932f93.png)

Worth noting that this issue only occurs when the `Inter var` font is used. Inter var is a variable font, and Firefox on Windows does not support variable fonts, at least according to this test file: https://rsms.me/inter/var-test.html

Since `Inter var` is the suggested font in the Tailwind UI docs, we should probably have a look at this.

I have crossed many situations where I had issues with input padding, line-height in Firefox, and had to set a fixed height instead. Wondering if the issue here is due to the variable font, as the input seems to behave correctly with other fonts.

Pinging @adamwathan who has probably been around the block a few times with input field cross-browser issues 😅

**Comment by simonswiss** [comment] 2020-10-02 02:36
So, I spoke to @davidluhr who is working primarily from a Windows machine using Firefox, and he mentioned that FF for Windows supports variable fonts since 2018, and your repro example displays properly (same height for input field) on his machine.

Just double checking - are you seeing this problem running from a "physical" Windows OS machine, or are you using something like a virtual machine from another OS? I was able to replicate the issue, but I did it on BrowserStack from my MacBook Pro 😅

**Comment by Wulfheart** [comment] 2020-10-02 06:00
I am using Windows 10 Enterprise Version 1803. The OS build is 17134.1610. However I don't remember it not working on my private machine, just on my work setup.

**Comment by simonswiss** [comment] 2020-10-05 04:11
Would be great if you can check! Thanks in advance. 👍

**Comment by davidluhr** [comment] 2020-11-23 19:32
Following up on this, @Wulfheart, are you still experiencing these issues?

The recent update to Tailwind UI also came with a new forms plugin that should help with cross-OS and browser form styling.

**Comment by davidluhr** [comment] 2021-01-22 23:44
Closing this issue for now as we haven't been able to recreate them on our end, but feel free to re-open if these issues still persist for you!

**Closed by davidluhr** 2021-01-22 23:44 UTC
Labels: bug
