### ISSUE TITLE
Native select dropdown, dropdown options not opening below select component

### ISSUE THREAD

**Issue by pedreviljoen** [tailwindlabs/tailwindui-issues#1615] opened 2024-07-24 13:42 UTC
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/select-menus
- Component name: Simply native

**Describe the bug**
The native select component on mobile renders the options dropdown list at a strange place, not under the select component. Replicated on the tailwind UI components site as well.

**To Reproduce**
Implement the native select input component with options, view that component on mobile viewport and click on the select component.

**Expected behavior**
Expected the select options to appear on top of or below the dropdown like below screenshot:

![Screenshot 2024-07-24 at 15 38 27](https://github.com/user-attachments/assets/9442ee48-14f0-4029-a99d-a1216f30d731)

**Screenshots**
![Screenshot 2024-07-24 at 15 30 14](https://github.com/user-attachments/assets/33ccd5f0-d853-4530-8c65-4df0eb0fa4e8)

**Browser/Device (if applicable)**
 - OS: iOS
 - Browser Chrome
 - Version: Chromium Engine Version 126.0.6478.183

**Comment by reinink** [comment] 2024-07-24 13:51
Hey! Thanks for letting us know about this.

I'm curious, are you seeing this behavior on a real mobile device, or just when using Chrome DevTools? (That's the only place I am able to reproduce this issue.)

Here's what I see in Chrome on my iPhone:

![IMG_DD495C07CFB0-1](https://github.com/user-attachments/assets/38949781-e998-4d54-bfa8-74cb4810a85d)

**Comment by reinink** [comment] 2024-08-07 21:21
Hey! Going to close this one for now because I'm 99% sure this is just an issue with DevTools and not something that will actually happen on a real device. Please let me know if that isn't the case though. Thanks! 🤙

**Closed by reinink** 2024-08-07 21:21 UTC
