### ISSUE TITLE
Appearance property not prefixed with webkit on Safari

### ISSUE THREAD

**Issue by jensdenies** [tailwindlabs/tailwindui-issues#1191] opened 2022-04-06 22:19 UTC
**What component (if applicable)**
- URL for category: [Link](https://tailwindui.com/components/application-ui/forms/select-menus#component-79592f355ca6f6e3b081e0158109981c)
- Component name: Simple native

**Describe the bug**
The styles of Tailwind seems to be overwritten by the default styling of Safari. When adding `-webkit-appearance: none;` it works again. Normally, this would be done by the `autoprefixer` of PostCSS, if I'm correct. This issue currently appears in a ReactJS application with the `autoprefixer` enabled. It's a new project started on React 18 and Tailwind 3.

**To Reproduce**
1. Create a ReactJS application with tailwind using the [tutorial](https://tailwindcss.com/docs/guides/create-react-app).
2. Use the `Simple native` component.
 
**Expected behavior**
When using the `Simple native` component it should shows me the same select box as in the example. Currently It gets overwritten by default Safari styling.

**Browser/Device (if applicable)**
 - OS: MacOS
 - Browser: Safari

**Comment by jensdenies** [comment] 2022-04-07 20:04
Hey @adamwathan, thanks for getting back to me. I just followed the ReactJS instructions from the Tailwind website. So I've got a file called: `postcss.config.js` in the root of my project with the following content:

```js
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
```

I also have `autoprefixer` with the following version constraint in the dev dependencies: `^10.4.4`.

Hope this helps.

**Comment by adamwathan** [comment] 2022-04-07 23:05
Hey! It would be a lot more helpful if you could create a GitHub repo that reproduces the problem if you can 👍🏻 If not I can try to create a project following your instructions myself when I have time but if it works for me then I can’t really tell you what to do 😅 if I can look at an actual project where it’s broken though I can definitely help.

**Comment by jensdenies** [comment] 2022-04-08 20:52
Hey @adamwathan, I've created a repository with the necessary code. It's private because I don't think the license allows to share it publicly. I invited you as a collaborator.

**Comment by adamwathan** [comment] 2022-04-10 13:41
Hey! Just cloned it and ran `npm run build` and the appearance property looks like it's properly prefixed to me in the production CSS:

<img width="846" alt="image" src="https://user-images.githubusercontent.com/4323180/162620631-6c3b6bdc-34b7-4b30-b115-9c75baf7c6f7.png">

But you're right, in development it's not being prefixed. Create React App doesn't actually support `postcss.config.js` files so your config there is actually being ignored, so I'm guessing internally CRA is only applying autoprefixer in production builds and not in development builds.

For this reason I generally discourage people from using CRA — the lack of configurability around pretty normal/basic things like this makes it a very frustrating experience. Instead I would recommend [Vite](https://vitejs.dev/) which provides the same overall experience for building single page React apps, but is much faster and more configurable, or [Next.js](https://nextjs.org/) or [Remix](https://remix.run/) if you want a more opinionated framework.

Seems like other people are having problems with autoprefixer in Create React App as well:

https://github.com/facebook/create-react-app/issues/9903

I'm going to close this just because there's nothing we can do on our end to fix the bug in CRA unfortunately 😞 Hopefully it gets resolved or you are able to use another tool that doesn't have this problem.

**Closed by adamwathan** 2022-04-10 13:41 UTC

**Comment by jensdenies** [comment] 2022-04-10 18:40
Hey @adamwathan, Thanks a lot for taking the time to look into this, I really enjoy TailwindUI! I think I'll switch to Vite to avoid this problem. 👍🏼
