### ISSUE TITLE
Bug: `Button Groups` -> `With checkbox and dropdown`

### ISSUE THREAD

**Issue by mertasan** [tailwindlabs/tailwindui-issues#1056] opened 2021-11-09 07:04 UTC
**What component (if applicable)**
- URL for category: [With checkbox and dropdown](https://tailwindui.com/components/application-ui/elements/button-groups#component-9e4d2ae1944600eac288621ec31cf6e2)
- Component name: With checkbox and dropdown

I wanted to let you know that. 

`focus:z-10`

![dropdown](https://user-images.githubusercontent.com/13007665/140876669-c6736d26-6c3e-4d62-97a3-db4e981d6097.gif)

**Comment by reinink** [comment] 2021-11-09 13:08
Hey thanks for reporting this! This appears to be a Chrome bug — and only occurs when the component is within an iframe. This makes sense, since the component previews on the Tailwind UI website are shown in an iframe. 

I was not able to reproduce this in Firefox or Safari.

Here's a little demo:

https://user-images.githubusercontent.com/882133/140929419-4ec7885d-a472-4780-a518-a6a716ddf31c.mov

While this is an annoying bug, I don't actually believe this is an issue with Tailwind UI itself, so I'm going to close this. But thanks either way for bringing this to our attention. 👍

**Closed by reinink** 2021-11-09 13:08 UTC
