### ISSUE TITLE
custom colors

### ISSUE THREAD

**Issue by MincePie** [tailwindlabs/tailwindui-issues#1396] opened 2023-01-01 23:33 UTC
What version of Tailwind CSS are you using?

"tailwindcss": "^3.2.1"

What build tool (or framework if it abstracts the build tool) are you using?

"postcss-focus-visible": "^6.0.4",
"build": "next build",
"next": "13.0.2",

What version of Node.js are you using?

v18.12.1

What browser are you using?

Chrome

What operating system are you using?

mac

Reproduction URL

Your own salient template - try adding custom colors to the tailwind.config.js

Describe your issue

I just purchased your template code. I downloaded it, ran yarn, and yarn dev, and loaded the template.

Then, consistent with the theme customisation [documentation](https://tailwindcss.com/docs/adding-custom-styles), I tried to add colors to the config as follows:

colors: {
      'blue': '#1fb6ff',
      'pink': '#ff49db',
      'orange': '#ff7849',
      'green': '#13ce66',
      'gray-dark': '#273444',
      'gray': '#8492a6',
      'gray-light': '#d3dce6',
    },
This results in the CSS breaking in the template code. The margins of the containers are thrown out, the testimonials section is made subject to enormous quotation marks, the colors are not used. If I delete this code from the theme, these issues are removed. It doesn't make any difference if I change the hex values of the colours or otherwise.

Are the templates out of date? Can they be made to work with tailwind css?

**Comment by adamwathan** [comment] 2023-01-02 01:20
Hey! Can you share a full example of a config file that breaks the template? Has to be some subtle configuration error here as I can't reproduce this myself.

This is what I see when making that change:

<img width="3001" alt="image" src="https://user-images.githubusercontent.com/4323180/210189450-da3ad0ad-ffae-42da-aabe-6e7a290e0666.png">

Some colors are broken because they are being completely overridden (for example the entire blue scale has been replaced by a single `blue` color, so colors like `blue-500` no longer work) which is expected and is just Tailwind doing what you're telling it to do, but I see no issues with margins or anything changing in size.

**Comment by MincePie** [comment] 2023-01-02 19:19
Hi @adamwathan 

This is the config file. It's copied straight from Salient.

Some people have made suggestions on the discord channel (general) - where I have also left screen shots of some of the weird consequences of trying to change colors in this template.

```
const defaultTheme = require('tailwindcss/defaultTheme')
// const colors = require('tailwindcss/colors')


/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx}'],
  
  theme: {
    // colors: {
    //   'blue': '#1fb6ff',
    //   'pink': '#ff49db',
    //   'orange': '#ff7849',
    //   'green': '#13ce66',
    //   'gray-dark': '#273444',
    //   'gray': '#8492a6',
    //   'gray-light': '#d3dce6',
    // },
  //   colors: {
  //     transparent: 'transparent',
  //     current: 'currentColor',
  //     'white': '#ffffff',
  //     'purple': '#3f3cbb',
  //     'midnight': '#121063',
  //     'metal': '#565584',
  //     'tahiti': '#3ab7bf',
  //     'silver': '#ecebff',
  //     'bubble-gum': '#ff77e9',
  //     'bermuda': '#78dcca',
  //   },
  // },
    fontSize: {
      xs: ['0.75rem', { lineHeight: '1rem' }],
      sm: ['0.875rem', { lineHeight: '1.5rem' }],
      base: ['1rem', { lineHeight: '1.75rem' }],
      lg: ['1.125rem', { lineHeight: '2rem' }],
      xl: ['1.25rem', { lineHeight: '2rem' }],
      '2xl': ['1.5rem', { lineHeight: '2rem' }],
      '3xl': ['2rem', { lineHeight: '2.5rem' }],
      '4xl': ['2.5rem', { lineHeight: '3.5rem' }],
      '5xl': ['3rem', { lineHeight: '3.5rem' }],
      '6xl': ['3.75rem', { lineHeight: '1' }],
      '7xl': ['4.5rem', { lineHeight: '1.1' }],
      '8xl': ['6rem', { lineHeight: '1' }],
      '9xl': ['8rem', { lineHeight: '1' }],
    },
    
    extend: {
      // the tailwind docs show these colors defined above, not in the extend object, but i tried adding them here as well
      // colors: {
    //   'blue': '#1fb6ff',
    //   'pink': '#ff49db',
    //   'orange': '#ff7849',
    //   'green': '#13ce66',
    //   'gray-dark': '#273444',
    //   'gray': '#8492a6',
    //   'gray-light': '#d3dce6',
    // },
  //   colors: {
  //     transparent: 'transparent',
  //     current: 'currentColor',
  //     'white': '#ffffff',
  //     'purple': '#3f3cbb',
  //     'midnight': '#121063',
  //     'metal': '#565584',
  //     'tahiti': '#3ab7bf',
  //     'silver': '#ecebff',
  //     'bubble-gum': '#ff77e9',
  //     'bermuda': '#78dcca',
  //   },
  // },
      borderRadius: {
        '4xl': '2rem',
      },
      fontFamily: {
        sans: ['Inter', ...defaultTheme.fontFamily.sans],
        display: ['Lexend', ...defaultTheme.fontFamily.sans],
      },
      maxWidth: {
        '2xl': '40rem',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}

```

**Comment by MincePie** [comment] 2023-01-02 19:35
How can I find out which colors have been overwritten? I can see from the template that blue has been used in some places. When I tried to replace it with 'green' the color renders as black. Maybe that has something to do with the change you're describing being applied to blue but not green. Is that rule set described somewhere?

**Comment by adamwathan** [comment] 2023-01-02 19:46
So I pasted in that entire config that you shared and I still don't see what you're saying you see — all of the margins, spacing, sizing, etc. all looks normal:

<img width="3006" alt="image" src="https://user-images.githubusercontent.com/4323180/210272731-59322d87-9ad0-4037-abdd-71db80fbb270.png">

> How can I find out which colors have been overwritten?

So if you read our documentation on [theme configuration](https://tailwindcss.com/docs/theme#customizing-the-default-theme) you can see how extending the theme vs. overriding the theme works.

Any colors that you specify under `colors` will override the defaults unless you put them under extend, so to answer your questions about "which colors have been overwritten" that's really just up to you and what colors you put in there.

> When I tried to replace it with 'green' the color renders as black.

What's happening here is you are replacing `blue` with a single color and not an object. By default, `blue` is an object with multiple shades:

```js
  // ...
  blue: {
    50: '#eff6ff',
    100: '#dbeafe',
    200: '#bfdbfe',
    300: '#93c5fd',
    400: '#60a5fa',
    500: '#3b82f6',
    600: '#2563eb',
    700: '#1d4ed8',
    800: '#1e40af',
    900: '#1e3a8a',
  },
  // ...
```

That's where utilities like `bg-blue-500` come from. So when you customize that to just be this:

```js
  // ...
  blue: 'green',
  // ...
```

Now anywhere colors like `bg-blue-500` were being used will just be nothing, because you've gotten rid of the `500` shade and now only have a single `bg-blue` utility.

**Comment by MincePie** [comment] 2023-01-02 19:51
i just deleted and reinstalled node, I don't know why that has helped with some of this, but I still can't figure out where blue is getting its definition. I'm still using the word blue (the same as the salient template), but have tried to override its value in the config with a hex value of a different shade.

**Comment by adamwathan** [comment] 2023-01-02 20:08
>  I think I'm changing the value of blue (which is used without a shade variant in the salient template (eg: the register button)

There's definitely no blue without a shade in the template, here's the code for the "Get started today" button which is what I'm guessing you mean by register button:

```html
<a class="group inline-flex items-center justify-center rounded-full py-2 px-4 text-sm font-semibold focus:outline-none focus-visible:outline-2 focus-visible:outline-offset-2 bg-blue-600 text-white hover:text-slate-100 hover:bg-blue-500 active:bg-blue-800 active:text-blue-100 focus-visible:outline-blue-600" href="/register">
  <span>Get started <span class="hidden lg:inline">today</span></span>
</a>
```

Can see there the background color is `bg-blue-600`.

There is no `blue` in the config file for the template either, there's actually no color overrides so I'm not sure what you mean when you say "change the hex value to a green shade":

```js
const defaultTheme = require('tailwindcss/defaultTheme')

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx}'],
  theme: {
    fontSize: {
      xs: ['0.75rem', { lineHeight: '1rem' }],
      sm: ['0.875rem', { lineHeight: '1.5rem' }],
      base: ['1rem', { lineHeight: '1.75rem' }],
      lg: ['1.125rem', { lineHeight: '2rem' }],
      xl: ['1.25rem', { lineHeight: '2rem' }],
      '2xl': ['1.5rem', { lineHeight: '2rem' }],
      '3xl': ['2rem', { lineHeight: '2.5rem' }],
      '4xl': ['2.5rem', { lineHeight: '3.5rem' }],
      '5xl': ['3rem', { lineHeight: '3.5rem' }],
      '6xl': ['3.75rem', { lineHeight: '1' }],
      '7xl': ['4.5rem', { lineHeight: '1.1' }],
      '8xl': ['6rem', { lineHeight: '1' }],
      '9xl': ['8rem', { lineHeight: '1' }],
    },
    extend: {
      borderRadius: {
        '4xl': '2rem',
      },
      fontFamily: {
        sans: ['Inter', ...defaultTheme.fontFamily.sans],
        display: ['Lexend', ...defaultTheme.fontFamily.sans],
      },
      maxWidth: {
        '2xl': '40rem',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
```

What are you changing? Where are you seeing just `blue` anywhere in the template?

**Comment by MincePie** [comment] 2023-01-02 20:44
The template has a few places where color='blue'. I'm not at my desk now, but ill come back to you tonight with references. Thank you for your help.

**Comment by adamwathan** [comment] 2023-01-02 21:15
Ah ok so when you see `<Button color="blue" ...>`, `color` is a prop on the React component, and `blue` is the value for the prop, not a CSS class. If you look in `Button.jsx` you can see all the classes that get added when you pass the `blue` prop:

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/4323180/210278480-77f85f45-e31f-4a6b-bbce-6b7830a57d61.png">

**Comment by adamwathan** [comment] 2023-01-03 17:20
I'm going to close this as I think we've gotten to the root of the misunderstanding here and there doesn't appear to be any actual bug in the template. If you'd like to talk through customizing the template to your needs with others in the community I'd recommend joining the [Tailwind UI Discord server](https://tailwindui.com/discord) 👍

**Closed by adamwathan** 2023-01-03 17:20 UTC
