### ISSUE TITLE
Missing default null value for useRef hook

### ISSUE THREAD

**Issue by roydigerhund** [tailwindlabs/tailwindui-issues#599] opened 2021-04-30 21:13 UTC
**What component (if applicable)**
- URL for category:  https://tailwindui.com/components/application-ui/overlays/modals
- Component name: all modals with a cancel button

**Describe the bug**
The correct usage of the useRef hook would include `null` as an initial value.
In a Javascript project, this would possibly don't matter but in a Typescript project this will throw an error because a `ref` attribute would not accept `undefined` as value.

**Current wrong usage**
`const cancelButtonRef = useRef()`

**Correct usage**
`const cancelButtonRef = useRef(null)`

**Headless UI**
The same wrong usage can be found in the Headless UI project, for example in the corresponding documentation for the Dialog component here: https://headlessui.dev/react/dialog

**Edit**
Linked issue on Headless UI:
https://github.com/tailwindlabs/headlessui/issues/473

**Comment by davidluhr** [comment] 2021-05-03 16:04
@roydigerhund Thanks for reporting this! It does indeed seem to originate in Headless UI. If you wouldn't mind, could you submit an issue there to help address the cause of this? https://github.com/tailwindlabs/headlessui/issues

I'll leave this issue open here for now to track things.

Thank you so much!

**Comment by roydigerhund** [comment] 2021-05-03 21:40
@davidluhr I created a related issue on the Headless UI repo: https://github.com/tailwindlabs/headlessui/issues/473

**Comment by davidluhr** [comment] 2021-05-04 15:30
@roydigerhund Thank you so much for doing that. It's a huge help!

**Comment by davidluhr** [comment] 2021-05-14 20:33
@roydigerhund Looks like everything is fixed on the Headless UI side of things, and I got the Tailwind UI components updated, so this should be all set now.

Thanks for providing a fix! The corrected versions will be live on the site soon.

**Closed** 2021-05-14 20:32 UTC
Labels: bug
