### ISSUE TITLE
Navigation (flyout) menu does not close when using React <Link />

### ISSUE THREAD

**Issue by kmyn** [tailwindlabs/tailwindui-issues#1090] opened 2021-12-12 03:28 UTC
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/ecommerce/components/store-navigation
- Component name: Store Navigation (`With featured categories`)

**Describe the bug**
Flyout menu does not close after clicking on menu link (using `<Link />` instead of `<a>`) in React.

**To Reproduce**
In React, when using `<Link />` instead of `<a>` (anchor tag), the flyout menu does not close once the link (category) link is clicked. The new page opens in the background but the foreground still show the open menu.

**Expected behavior**
Menu should close once the link is clicked when using `<Link>` component in react.

**Browser/Device (if applicable)**
 - Desktop Chrome.

**Comment by JacobJaffe** [comment] 2022-01-21 20:32
By `Link`, I'm guessing you're talking about `next/Link`. **I think this is a Headless UI & NextJs issue** -- there seems to a few issues with using `Link` inside of `Disclosure` or inside of `Menu`. 

For anyone this might help, here are my workarounds for this. I'd love to hear from if the tailwindcss folks have suggestions on better practices. 

## Menu:

Here, I wrap the component in a `div`. This isn't great accessibility wise, but otherwise the `Link` doesn't get
the `role=menuitem` attribute added to it, and thus doesn't receive hover events.

```tsx
<Menu.Item>
    {({ active }) => (
      <div> //  <-- this shouldn't be needed!
        <Link href={href} passHref>
          <a
            className={classNames(
              active ? "bg-gray-100" : "",
              "block px-4 py-2 text-sm text-gray-700"
            )}
          >
            {title}
          </a>
        </Link>
      </div>
    )}
  </Menu.Item>
```

## Disclosure:
This is similar to the flyout issue, I think. Here, instead of using the automatic closing, you can wire the provided `close` prop to your components:

```tsx
<Disclosure.Panel className="sm:hidden">
    {({ close }) => (
      <Link href={href} passHref>
        <a
          onClick={() => void close()} // <-- this ideally shouldn't be needed, but it fixed the issues.
        >
          {linkTitle}
        </a>
      </Link>
    )}
  </Disclosure.Panel>
  ```

**Comment by RobinMalfait** [comment] 2022-01-21 20:47
Hey! Thank you for your bug report!
Much appreciated! 🙏

The issue is because the `Menu.Item` puts some props on the first child if you didn't provide an `as` prop. This means that we will put props on the `Link` component. The issue with that is that the `Link` component doesn't forward props to the underlying component.

The trick is my creating your own custom `Link` component that **does** forward the props. More info on that can be found here: https://headlessui.dev/react/menu#integrating-with-next-js

Example from the link above:
```js
import Link from 'next/link'
import { Menu } from '@headlessui/react'

function MyLink(props) {
  let { href, children, ...rest } = props
  return (
    <Link href={href}>
      <a {...rest}>{children}</a>
    </Link>
  )
}

function Example() {
  return (
    <Menu>
      <Menu.Button>More</Menu.Button>
      <Menu.Items>
        <Menu.Item>
          <MyLink href="/profile">Profile</MyLink>
        </Menu.Item>
      </Menu.Items>
    </Menu>
  )
}
```

**Closed by RobinMalfait** 2022-01-21 20:47 UTC
