### ISSUE TITLE
Bug in the "full-width with sidebar" home screens page example

### ISSUE THREAD

**Issue by frouo** [tailwindlabs/tailwindui-issues#1354] opened 2022-10-31 17:44 UTC
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/page-examples/home-screens#component-af4086fe483fb8a418175cf0218dd5c4
- Component name: [Full-width with sidebar](https://tailwindui.com/components/application-ui/page-examples/home-screens#component-af4086fe483fb8a418175cf0218dd5c4)

**Describe the bug**

<img width="275" alt="image" src="https://user-images.githubusercontent.com/2499356/199072425-ccfac55a-b823-42cd-9466-367fea8c4bee.png">

**To Reproduce**
1. Go to 'application ui / page examples / home screens / Full-width with sidebar'
2. Click on 'Jessy Schwarz'

**Expected behavior**
The purple border top should be visible.

**Browser/Device (if applicable)**
 - OS: macos monterey  12.6
 - Browser: chrome
 - Version 106.0.5249.119 (Official Build) (x86_64)

**Comment by bradlc** [comment] 2022-11-01 10:30
Closing this as a duplicate of #1348

**Closed by bradlc** 2022-11-01 10:30 UTC

**Comment by frouo** [comment] 2022-11-01 11:09
👍🏻 sorry for the duplicate 🙏🏻
