### ISSUE TITLE
For inputs need ring fixes

### ISSUE THREAD

**Issue by jacwright** [tailwindlabs/tailwindui-issues#1367] opened 2022-11-14 17:08 UTC
**What component (if applicable)**
- URL for category: https://tailwindui.com/components/application-ui/forms/form-layouts
- Component name: Inputs

**Describe the bug**
It appears the version of Tailwind which is used in the form layouts doesn't require `ring-1` to make rings show up like Tailwind 3 seems to, and the browser's default `outline` on focus-visible covers the box-shadow of rings.

**To Reproduce**
Implement the form inputs exactly as the page shows and the default browser outline on Chrome will be what is visible.

**Expected behavior**
To fix, these classes are needed in addition to what exists in input: `outline-none focus:ring-1`.

**Comment by adamwathan** [comment] 2022-11-14 17:24
Hey! Just to be sure, have you installed and added the `@tailwindcss/forms` plugin to your project? I can't reproduce this myself as long as the plugin is configured for the project:

https://play.tailwindcss.com/t6PaQ8G3Y6

**Comment by adamwathan** [comment] 2022-11-16 10:53
Going to close this one for now as I expect the answer is to install + configure the forms plugin as I mentioned in my last comment. If you're still having issues though don't hesitate to open a new issue but include a reproduction with it so we can actually test it out and figure out what's wrong 👍

**Closed by adamwathan** 2022-11-16 10:53 UTC
