### ISSUE TITLE
Modal not working 

### ISSUE THREAD

**Issue by brainlet-ali** [tailwindlabs/tailwindui-issues#1257] opened 2022-07-09 06:45 UTC
**What component (if applicable)**
- URL for category: 
- Component name: 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser/Device (if applicable)**

**Additional context**

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `zo`.

**Comment by reinink** [comment] 2022-07-11 18:05
@brainlet-ali Hey! Sorry you bumped into this. I would love to help you out, but based on the information you gave me I'm not sure what the the problem is here, since you didn't fill out the issue template.

I'm going to close this since there is no action I can take here, but if you haven't solved this yet, please create a new issue with all the necessary information 👍

**Closed by reinink** 2022-07-11 18:05 UTC

**Comment by brainlet-ali** [comment] 2022-07-12 06:26
What component (if applicable)

URL for category: https://tailwindui.com/components/application-ui/overlays/modals
Component name: [Centered with single action](https://tailwindui.com/components/application-ui/overlays/modals#component-31555aec01de5027d6696629eb60f673)
Describe the bug
**When I try to embed this component into my page I get this:**

1 of 2 unhandled errors

Unhandled Runtime Error
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `zo`.

Call Stack
createFiberFromTypeAndProps
node_modules/react-dom/cjs/react-dom.development.js (28221:0)
createFiberFromElement
node_modules/react-dom/cjs/react-dom.development.js (28247:0)
reconcileSingleElement
node_modules/react-dom/cjs/react-dom.development.js (15583:0)
reconcileChildFibers
node_modules/react-dom/cjs/react-dom.development.js (15641:0)
reconcileChildren
node_modules/react-dom/cjs/react-dom.development.js (19909:0)
updateContextProvider
node_modules/react-dom/cjs/react-dom.development.js (21922:0)
beginWork
node_modules/react-dom/cjs/react-dom.development.js (22404:0)
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js (4157:0)
Object.invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js (4206:0)
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js (4270:0)
beginWork$1
node_modules/react-dom/cjs/react-dom.development.js (27243:0)
performUnitOfWork
node_modules/react-dom/cjs/react-dom.development.js (26392:0)
workLoopSync
node_modules/react-dom/cjs/react-dom.development.js (26303:0)
renderRootSync
node_modules/react-dom/cjs/react-dom.development.js (26271:0)
performConcurrentWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js (25577:0)
workLoop
node_modules/scheduler/cjs/scheduler.development.js (266:0)
flushWork
node_modules/scheduler/cjs/scheduler.development.js (239:0)
MessagePort.performWorkUntilDeadline
node_modules/scheduler/cjs/scheduler.development.js (533:0)

Check the render method of zo.


Screenshots
If applicable, add screenshots to help explain your problem.
![FireShot Capture 349 -  - localhost](https://user-images.githubusercontent.com/16162821/178423087-b76a089c-67c8-4233-9518-5c3d4621c165.png)
