### ISSUE TITLE
zIndex, even if empty, in config breaks hero component

### ISSUE THREAD

**Issue by grempe** [tailwindlabs/tailwindui-issues#277] opened 2020-08-13 05:01 UTC
**What component (if applicable)**

- URL for category: https://tailwindui.com/components/marketing/sections/heroes
- Component name: With angled image on right

**Describe the bug**

I was having issues related to z-index when using the nav bars with drop downs and typography plugin where if the drop down covered an `<ul>` section of the page the `ul` (but not paragraphs) would show through the drop down and sit on top of it.

This led me to experiment with adding a zIndex setting in my config like:

```
const defaultTheme = require("tailwindcss/defaultTheme")

module.exports = {
...
  theme: {
    zIndex: {},
  }
...
}
```

While I was able to get the `ul` issue at least temporarily solved (but this should not have to be done out of the box) I found that adding even an empty object for the `zIndex` value breaks the angle portion of the photo in this component. It will instead show a vertical border on the left.

The behavior is the same if `zIndex` extra values are specified as well.

**To Reproduce**

Add an empty `zIndex` object in the config.

**Expected behavior**

The photo in this component should have an angled left edge.

**Comment by simonswiss** [comment] 2020-08-13 10:52
Hey! 👋

If you add an empty `zIndex` object directly into your `theme` in the config, you'll effectively **override** the z-index options, and erase them all.

The angle on the image for that hero is created by an SVG slant overlay, which is positioned over the image with a `z-10` class. I made this SVG purple instead of white in the screenshot below so you can see what's happening. 👍 

![image](https://user-images.githubusercontent.com/485747/90125356-45495e80-dda5-11ea-97ef-223c343513b3.png)

Without the `z-10` class, the SVG goes behind the image, which is why it now looks vertical!

![image](https://user-images.githubusercontent.com/485747/90125661-bdb01f80-dda5-11ea-85aa-f03c6159b1a6.png)

If you want to **add values** to the `zIndex` object without removing the existing ones, you need to `extend` the theme like so:

```javascript
module.exports = {
  theme: {
    extend: {
      zIndex: {}
    }
  }
}
```

Here's the link on how to extend the default theme in the [Tailwind CSS documentation](https://tailwindcss.com/docs/theme#extending-the-default-theme).

As per the dropdown and `ul` stacking clash - perhaps try to set your dropdown menu position to `relative`.

Hope it helps! 👍 

I'll close this since this is probably not a bug. If you need more support, I suggest you [join the Discord community](https://tailwindui.com/discord)!

**Closed by simonswiss** 2020-08-13 10:52 UTC
Labels: bug

**Comment by grempe** [comment] 2020-08-13 16:39
That was a perfect answer. Thank you. And I appreciate you taking the time to help me learn more.
